name: Test

on: [push, pull_request]

jobs:
  generate-examples:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Start Kind cluster
      run: make setup-kind

    - name: Wait for cluster to be ready
      run: make generate-examples

    - name: Check for modified files
      run: |
        modified_files=$(git diff)
        if [ -n "$modified_files" ]; then
          echo "Working directory has changes:"
          echo $modified_files
          exit 1
        fi
